apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkins/jenkins:2.303.1
        name: jenkins
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1500m
            memory: 2Gi
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
      terminationGracePeriodSeconds: 120
      volumes:
      - name: jenkins-home
        nfs:
          path: /storage/jenkins_home
          server: {{ .Values.nfs_private_ip | quote }}
