kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: vault
  namespace: vault
spec:
  rules:
  - host: {{ .Values.domain | quote }}
    http:
      paths:
      - backend:
          service:
            name: vault
            port:
              number: 8200
        pathType: Prefix
        path: /
