kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: vault
  namespace: vault
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: {{ .Values.domain | quote }}
    http:
      paths:
      - backend:
          service:
            name: vault
            port:
              number: 8200
        pathType: Prefix
        path: /
  tls:
  - hosts:
    - {{ .Values.domain | quote }}
    secretName: vault-tls
