apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  annotations:
    traefik.ingress.kubernetes.io/service.serverstransport: "test"
spec:
  selector:
    app: vault
  ports:
  - name: "8200"
    port: 8200
