apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-export
spec:
  schedule: "0 3,15 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      completions: 1
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: backup
              image: {{ .Values.vaultExportImage | quote }}
              command:
                - bash
                - -c
                - |
                  export VAULT_TOKEN="$(vault write -format=json auth/approle/login role_id=$AVP_ROLE_ID \
                    secret_id=$AVP_SECRET_ID | jq -r .auth.client_token)" &&\
                  cd $(mktemp -d) &&\
                  vault_export.py export.json.gpg &&\
                  FILENAME="/opt/backup/$(date +%Y-%m-%d-%H).json.gpg" &&\
                  echo "Saving export at ${FILENAME}" &&\
                  mv export.json.gpg "${FILENAME}" &&\
                  find /opt/backup -type f -mtime +30 -delete &&\
                  ls -lah /opt/backup
              envFrom:
                - secretRef:
                    name: vaultbackup
              volumeMounts:
                - name: backup
                  mountPath: /opt/backup
          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: state-db-backup
