stateDb:
  # pulled Sep 18, 2022
  image: postgres:14@sha256:b0ee049a2e347f5ec8c64ad225c7edbc88510a9e34450f23c4079a489ce16268
  resources:
    requests:
      memory: 250Mi
      cpu: 50m
    limits:
      memory: 500Mi
      cpu: 100m

secrets:
  - name: state-db
    data:
      POSTGRES_PASSWORD: "~vault:iac/terraform/state_db:backend-db-password~"
      server.key: "~vault:iac/terraform/state_db:state_db_server.key~"
      server.crt: "~vault:iac/terraform/state_db:state_db_server.crt~"
