apiVersion: apps/v1
kind: Deployment
metadata:
  name: binaries-nginx
spec:
  selector:
    matchLabels:
      app: binaries-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: binaries-nginx
    spec:
      terminationGracePeriodSeconds: 2
      containers:
        - name: nginx
          # Pulled Dec 8, 2022
          image: nginx@sha256:ab589a3c466e347b1c0573be23356676df90cd7ce2dbf6ec332a5f0a8b5e59db
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: webroot
              mountPath: /usr/share/nginx/html
      volumes:
        - name: webroot
          nfs:
            path: /storage/cloudcli
            server: {{ .Values.nfs_private_ip | quote }}
