apiVersion: v1
kind: ServiceAccount
metadata:
  name: certbot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: certbot
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["delete", "create", "get", "patch", "update", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certbot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: certbot
subjects:
- kind: ServiceAccount
  name: certbot
  namespace: cloudcli
