apiVersion: batch/v1
kind: CronJob
metadata:
  name: certbot
spec:
  schedule: "0 0,12 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      completions: 1
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: certbot
          containers:
            - name: certbot
              image: {{ .Values.certbot_image }}
              command:
                - bash
                - -c
                - |
                  certbot_.py "~iac:cloudcli_server_domain~" "~iac:letsencrypt_email~" --renew --html \
                    --ssl-secret-name=cloudcli-server-tls \
                    --ssl-secret-namespace=cloudcli
              env:
                - name: WEBROOT_PATH
                  value: /var/www/html
              volumeMounts:
                - name: certbot-webroot
                  mountPath: /var/www/html
                - name: certbot
                  mountPath: /etc/letsencrypt
                  subPath: etc_letsencrypt
                - name: certbot
                  mountPath: /var/lib/letsencrypt
                  subPath: var_lib_letsencrypt
          volumes:
            - name: certbot-webroot
              persistentVolumeClaim:
                claimName: certbot-webroot
            - name: certbot
              persistentVolumeClaim:
                claimName: certbot
