apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcli-k8s
spec:
  replicas: {{ .Values.k8s.replicas }}
  selector:
    matchLabels:
      app: cloudcli-k8s
  template:
    metadata:
      labels:
        app: cloudcli-k8s
    spec:
      terminationGracePeriodSeconds: 240
      containers:
      - name: cloudcli-k8s
        image: ghcr.io/kamatera/cloudcli-server-kubernetes:{{ .Values.k8s.version }}
        resources: {{ toYaml .Values.k8s.resources | nindent 10 }}
        ports:
          - containerPort: 8000
