apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcli-server
spec:
  replicas: {{ .Values.minReplicas }}
  selector:
    matchLabels:
      app: cloudcli-server
  template:
    metadata:
      labels:
        app: cloudcli-server
    spec:
      terminationGracePeriodSeconds: 240
      containers:
      - name: cloudcli-server
        image: {{ .Values.image }}
        env:
        - name: CLOUDCLI_API_SERVER
          value: https://console.kamatera.com
        - name: CLOUDCLI_PROVIDER
          value: proxy
        - name: K8S_OPENAPI_SCHEMA_URL
          value: http://cloudcli-k8s:8080/k8s/openapi.json
        startupProbe:
          httpGet: {port: 80, path: /}
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 3
          failureThreshold: 10
        readinessProbe:
          httpGet: {port: 80, path: /}
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 3
          failureThreshold: 2
        livenessProbe:
          httpGet: {port: 80, path: /}
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 3
          failureThreshold: 2
        resources:
          requests:
            cpu: 1000m
            memory: 1024Mi
          limits:
            cpu: 2000m
            memory: 2148Mi
