{{ if false }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudcli-server
spec:
  secretName: cloudcli-server-tls
  dnsNames:
    - {{ .Values.cloudcliServerDomain | quote }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  usages:
    - digital signature
    - key encipherment
{{ end }}
