apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudcli-schema-nginx-conf
data:
  default.conf: |
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:1m max_size=10m inactive=1w use_temp_path=off;

    server {
      listen 80;
      server_name localhost;
      location = /schema {
          proxy_cache my_cache;
          proxy_cache_valid 1m;
          proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
          proxy_pass http://cloudcli-server/schema;
      }
    }
