apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudcli-server
spec:
  ingressClassName: nginx
  rules:
    - host: "~iac:cloudcli_server_domain~"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloudcli-server
                port:
                  number: 80
