apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcli-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudcli-k8s
  template:
    metadata:
      labels:
        app: cloudcli-k8s
    spec:
      terminationGracePeriodSeconds: 240
      containers:
      - name: cloudcli-k8s
        image: ghcr.io/kamatera/cloudcli-server-kubernetes:58aaa16e084a913719ea552f372d182479b2030f
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            memory: 1024Mi
