apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudcli-server
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "20"  # default = 5
    nginx.ingress.kubernetes.io/proxy-read-timeout: "240"  # default = 60
    nginx.ingress.kubernetes.io/proxy-send-timeout: "240"  # default = 60
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.cloudcliServerDomain | quote }}
      secretName: cloudcli-server-tls
  rules:
    - host: {{ .Values.cloudcliServerDomain | quote }}
      http:
        paths:
          - path: /.well-known
            pathType: Prefix
            backend:
              service:
                name: certbot-nginx
                port:
                  number: 80
          - path: /binaries
            pathType: Prefix
            backend:
              service:
                name: binaries-nginx
                port:
                  number: 80
          - path: /k8s
            pathType: Prefix
            backend:
              service:
                name: cloudcli-k8s
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloudcli-server
                port:
                  number: 80
