apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: kamateratoolbox-pages
spec:
  entrypoint: deploy
  templates:
    - name: deploy
      container:
        image: ghcr.io/kamatera/kamateratoolbox:aa88aafdcac66b3c2347dae4160fe1d7f20eb236
        envFrom:
          - secretRef:
              name: kamateratoolbox-pages
        command:
          - bash
          - bin/deploy.sh