secrets:
- name: prometheus-httpauth
  data:
    "~vault_raw:iac/apps/httpauth/prometheus:username~": "~vault:iac/apps/httpauth/prometheus:httpauth_password~"

kube-prometheus-stack:

  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - cloudcli-grafana.~iac:root_domain~
    persistence:
      enabled: true

  prometheus:
    prometheusSpec:
      retention: 10d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 100Gi

  kubelet:
    serviceMonitor:
      cAdvisorRelabelings:
        - sourceLabels: [ __metrics_path__ ]
          targetLabel: metrics_path
        - sourceLabels: [ __metrics_path__ ]
          targetLabel: container
          replacement: "-"
        - sourceLabels: [ __metrics_path__ ]
          targetLabel: image
          replacement: "-"
        - sourceLabels: [ __metrics_path__ ]
          targetLabel: cluster
          replacement: cloudcli

  kube-state-metrics:
    prometheus:
      monitor:
        relabelings:
          - sourceLabels: [ __metrics_path__ ]
            targetLabel: cluster
            replacement: cloudcli
