secrets:
- name: prometheus-httpauth
  data:
    "~vault_raw:iac/apps/httpauth/prometheus:username~": "~vault:iac/apps/httpauth/prometheus:httpauth_password~"

kube-prometheus-stack:

  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - cloudcli-grafana.~iac:root_domain~
    persistence:
      enabled: true

  prometheus:
    prometheusSpec:
      retention: 10d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 100Gi

  prometheus-node-exporter:
    priorityClassName: system-node-critical
    tolerations:
      - operator: Exists
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
        effect: NoExecute
