infra_apps:

- name: vault
  disableAutoSync: true
  project: infra
  destinationNamespace: vault
  source:
    repoURL: https://github.com/Kamatera/kamateratoolbox-iac.git
    targetRevision: main
    path: apps/vault
  sourceVaultPluginHelmValueFiles:
  - values.yaml

- name: terraform
  disableAutoSync: true
  project: infra
  destinationNamespace: terraform
  source:
    repoURL: https://github.com/Kamatera/kamateratoolbox-iac.git
    targetRevision: main
    path: apps/terraform
  sourceVaultPluginHelmValueFiles:
  - values.yaml

- name: monitoring-kube-prometheus-crds
  disableAutoSync: true
  project: infra
  destinationNamespace: monitoring
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    # this version should match version defined in apps/monitoring/Chart.yaml
    targetRevision: kube-prometheus-stack-39.11.0
    directory:
      recurse: true

- name: monitoring
  disableAutoSync: true
  project: infra
  destinationNamespace: monitoring
  source:
    repoURL: https://github.com/Kamatera/kamateratoolbox-iac.git
    targetRevision: main
    path: apps/monitoring
  sourceVaultPluginHelmValueFiles:
  - values.yaml
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: monitoring-kube-prometheus-admission
      jsonPointers:
          - /webhooks/0/failurePolicy
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: monitoring-kube-prometheus-admission
      jsonPointers:
          - /webhooks/0/failurePolicy

- name: cluster-autoscaler
  disableAutoSync: true
  project: infra
  destinationNamespace: kube-system
  source:
    repoURL: https://github.com/Kamatera/kamateratoolbox-iac.git
    targetRevision: main
    path: apps/cluster-autoscaler

- name: backup
  disableAutoSync: true
  project: infra
  destinationNamespace: backup
  source:
    repoURL: https://github.com/Kamatera/kamateratoolbox-iac.git
    targetRevision: main
    path: apps/backup

- name: cluster-admin
  disableAutoSync: true
  project: infra
  destinationNamespace: cluster-admin
  source:
    repoURL: https://github.com/Kamatera/kamateratoolbox-iac.git
    targetRevision: main
    path: apps/cluster-admin
  sourceVaultPluginHelmValueFiles:
  - values.yaml

- name: argoworkflows-manifests
  disableAutoSync: true
  project: infra
  destinationNamespace: argo
  source:
    repoURL: https://github.com/Kamatera/kamateratoolbox-iac.git
    targetRevision: main
    path: apps/argoworkflows/manifests

- name: argoworkflows
  disableAutoSync: true
  project: infra
  destinationNamespace: argo
  source:
    repoURL: https://github.com/Kamatera/kamateratoolbox-iac.git
    targetRevision: main
    path: apps/argoworkflows
  sourceVaultPluginHelmValueFiles:
  - values.yaml
