projects:

  - name: infra
    spec:
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      destinations:
        - name: '*'
          namespace: vault
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: terraform
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: certbot
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - https://github.com/Kamatera/kamateratoolbox-iac.git
