projects:

  - name: infra
    spec:
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      destinations:
        - name: '*'
          namespace: vault
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: terraform
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: certbot
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: ingress-nginx
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: monitoring
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: kube-system
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: backup
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: cluster-admin
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: jenkins
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - https://github.com/Kamatera/kamateratoolbox-iac.git
        - https://github.com/prometheus-community/helm-charts.git

  - name: cloudcli
    spec:
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      destinations:
        - name: '*'
          namespace: cloudcli
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - https://github.com/Kamatera/kamateratoolbox-iac.git
