infra_apps:

- name: vault
  disableAutoSync: false
  project: infra
  destinationNamespace: vault
  source:
    repoURL: https://github.com/Kamatera/kamateratoolbox-iac.git
    targetRevision: main
    path: apps/vault
  sourceVaultPluginHelmValueFiles:
  - values.yaml

- name: terraform
  disableAutoSync: false
  project: infra
  destinationNamespace: terraform
  source:
    repoURL: https://github.com/Kamatera/kamateratoolbox-iac.git
    targetRevision: main
    path: apps/terraform
  sourceVaultPluginHelmValueFiles:
  - values.yaml

- name: certbot
  disableAutoSync: false
  project: infra
  destinationNamespace: certbot
  source:
    repoURL: https://github.com/Kamatera/kamateratoolbox-iac.git
    targetRevision: main
    path: apps/certbot
  sourceVaultPluginHelmValueFiles:
  - values.yaml
