apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ArgoServerDomain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-server
                port:
                  name: web
