apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-snapshots-backup
spec:
  schedule: "0 1,13 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      completions: 1
      backoffLimit: 0
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: cloudcli-prod-k3s-controlplace
          priorityClassName: system-node-critical
          tolerations:
            - operator: Exists
              effect: NoSchedule
            - key: CriticalAddonsOnly
              operator: Exists
            - operator: Exists
              effect: NoExecute
          restartPolicy: Never
          containers:
            - name: etcd
              # Pulled Dec 11, 2022
              image: alpine@sha256:8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4
              command:
                - sh
                - -c
                - |
                  tar -cvzf /opt/target/snapshot-$(date +%Y-%m-%d-%H-%M-%S).tar.gz /opt/source/db
              volumeMounts:
                - name: source
                  mountPath: /opt/source
                - name: target
                  mountPath: /opt/target
          volumes:
            - name: source
              hostPath:
                path: /var/lib/rancher/k3s/server
            - name: target
              persistentVolumeClaim:
                claimName: cluster-snapshots-backup
