certbot_image: ghcr.io/kamatera/kamateratoolbox-iac-certbot:3e6de1348a7e48771c849e24014adc5cf4a59e19
root_domain: "~iac:root_domain~"
letsencrypt_email: "~iac:letsencrypt_email~"
nfs_private_ip: "~iac:nfs_private_ip~"
rancher_private_ip: "~iac:rancher_private_ip~"

secrets:
- name: cloudflare
  data:
    api_token: "~vault:iac/cloudflare:api_token~"
