# Build from docker/certbot on Dec 11, 2022
certbot_image: ghcr.io/kamatera/kamateratoolbox-iac-certbot:2eaccb3f812ba4f6c4444647312f58cd94f4aa9b
root_domain: "~iac:root_domain~"
letsencrypt_email: "~iac:letsencrypt_email~"
nfs_private_ip: "~iac:nfs_private_ip~"
rancher_private_ip: "~iac:rancher_private_ip~"

secrets:
- name: cloudflare
  data:
    api_token: "~vault:iac/cloudflare:api_token~"
