certbot_image: ghcr.io/kamatera/kamateratoolbox-iac-certbot:70ab7fe29d95a34ea752ab03d9d28952fad5152c
root_domain: "~iac:root_domain~"
letsencrypt_email: "~iac:letsencrypt_email~"
nfs_private_ip: "~iac:nfs_private_ip~"
rancher_private_ip: "~iac:rancher_private_ip~"

secrets:
- name: cloudflare
  data:
    api_token: "~vault:iac/cloudflare:api_token~"
