# Build from docker/certbot on Dec 8, 2022
certbot_image: ghcr.io/kamatera/kamateratoolbox-iac-certbot:de13db0fd90a15ad5e1091e113852548ba5661bd
root_domain: "~iac:root_domain~"
letsencrypt_email: "~iac:letsencrypt_email~"

secrets:
- name: cloudflare
  data:
    api_token: "~vault:iac/cloudflare:api_token~"
