# Build from docker/certbot on Dec 8, 2022
certbot_image: ghcr.io/kamatera/kamateratoolbox-iac-certbot:70aa4f598cddb97906f3d9d48e979b0b3d249330
root_domain: "~iac:root_domain~"
letsencrypt_email: "~iac:letsencrypt_email~"

secrets:
- name: cloudflare
  data:
    api_token: "~vault:iac/cloudflare:api_token~"
