# Build from docker/certbot on Dec 8, 2022
certbot_image: ghcr.io/kamatera/kamateratoolbox-iac-certbot:d2b82aa99f91f400a2f19ce7093b19fc7458f21c
root_domain: "~iac:root_domain~"
letsencrypt_email: "~iac:letsencrypt_email~"

secrets:
- name: cloudflare
  data:
    api_token: "~vault:iac/cloudflare:api_token~"
