# Build from docker/certbot on Dec 11, 2022
certbot_image: ghcr.io/kamatera/kamateratoolbox-iac-certbot:c9b1c1c39f685b662bddfab69b9ce6b976f52b58
root_domain: "~iac:root_domain~"
letsencrypt_email: "~iac:letsencrypt_email~"
nfs_private_ip: "~iac:nfs_private_ip~"

secrets:
- name: cloudflare
  data:
    api_token: "~vault:iac/cloudflare:api_token~"
