certbot_image: ghcr.io/kamatera/kamateratoolbox-iac-certbot:2bde581c320cb02e81c86a202762b6153a02d3eb
root_domain: "~iac:root_domain~"
letsencrypt_email: "~iac:letsencrypt_email~"
nfs_private_ip: "~iac:nfs_private_ip~"
rancher_private_ip: "~iac:rancher_private_ip~"

secrets:
- name: cloudflare
  data:
    api_token: "~vault:iac/cloudflare:api_token~"
