image: kamatera/cloudcli-server:f6eaa842a41da846865927f0a75357d33a3fd4d9
# Built from docker/certbot on Dec 11, 2022
certbot_image: ghcr.io/kamatera/kamateratoolbox-iac-certbot:8433ac3d1ec7ee901afb3a8894d8a251d5a409dc
minReplicas: 4
maxReplicas: 15
cloudcliServerDomain: "cloudcli.cloudwm.com"
letsencryptEmail: "~iac:letsencrypt_email~"
nfs_private_ip: "~iac:nfs_private_ip~"

k8s:
  # version is the git hash from Kamatera/cloudcli-server-kubernetes repo
  version: 1faf91a426e6a49cb99a0a8114a2880cc6bd737c
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 1024Mi

secrets:
- name: build-cloudcli-binaries
  data:
    AWS_ACCESS_KEY_ID: "~vault:cloudcli/build-env:AWS_ACCESS_KEY_ID~"
    AWS_SECRET_ACCESS_KEY: "~vault:cloudcli/build-env:AWS_SECRET_ACCESS_KEY~"
    AWS_REGION: "~vault:cloudcli/build-env:AWS_REGION~"
    AWS_MAC_INSTANCE_AVAILABILITY_ZONE: "~vault:cloudcli/build-env:AWS_MAC_INSTANCE_AVAILABILITY_ZONE~"
    AWS_MAC_INSTANCE_ID: "~vault:cloudcli/build-env:AWS_MAC_INSTANCE_ID~"
    AWS_MAC_PEM_KEY_BASE64: "~vault:cloudcli/build-env:AWS_MAC_PEM_KEY_BASE64~"
    SSH_IP: "~vault:cloudcli/build-env:SSH_IP~"
    SSH_PRIVATE_KEY_BASE64: "~vault:cloudcli/build-env:SSH_PRIVATE_KEY_BASE64~"
