image: kamatera/cloudcli-server:f6eaa842a41da846865927f0a75357d33a3fd4d9
minReplicas: 4
maxReplicas: 15
cloudcliServerDomain: "cloudcli.cloudwm.com"
nfs_private_ip: "~iac:nfs_private_ip~"

k8s:
  # version is the git hash from Kamatera/cloudcli-server-kubernetes repo
  version: adc2658ac252ca25a592ff9f31d2db903403137e
  replicas: 3
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 500Mi
  worker:
    replicas: 4
    terminationGracePeriodSeconds: 3600
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        memory: 500Mi
  scheduler:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        memory: 500Mi
  flower:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        memory: 500Mi
  db:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        memory: 500Mi
  rabbitmq:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        memory: 500Mi

secrets:
- name: build-cloudcli-binaries
  data:
    AWS_ACCESS_KEY_ID: "~vault:cloudcli/build-env:AWS_ACCESS_KEY_ID~"
    AWS_SECRET_ACCESS_KEY: "~vault:cloudcli/build-env:AWS_SECRET_ACCESS_KEY~"
    AWS_REGION: "~vault:cloudcli/build-env:AWS_REGION~"
    AWS_MAC_INSTANCE_AVAILABILITY_ZONE: "~vault:cloudcli/build-env:AWS_MAC_INSTANCE_AVAILABILITY_ZONE~"
    AWS_MAC_INSTANCE_ID: "~vault:cloudcli/build-env:AWS_MAC_INSTANCE_ID~"
    AWS_MAC_PEM_KEY_BASE64: "~vault:cloudcli/build-env:AWS_MAC_PEM_KEY_BASE64~"
    SSH_IP: "~vault:cloudcli/build-env:SSH_IP~"
    SSH_PRIVATE_KEY_BASE64: "~vault:cloudcli/build-env:SSH_PRIVATE_KEY_BASE64~"
- name: cloudcli-k8s-celery
  data:
    POSTGRES_PASSWORD: "~vault:cloudcli/celery:POSTGRES_PASSWORD~"
    CELERY_RESULT_BACKEND: "~vault:cloudcli/celery:CELERY_RESULT_BACKEND~"
    CELERY_BROKER: "~vault:cloudcli/celery:CELERY_BROKER~"
