image: kamatera/cloudcli-server:ce74ad8a1dbd13f5dc101a82cf226afa65195701
# Build from docker/certbot on Dec 11, 2022
certbot_image: ghcr.io/kamatera/kamateratoolbox-iac-certbot:8433ac3d1ec7ee901afb3a8894d8a251d5a409dc
minReplicas: 4
maxReplicas: 15
cloudcliServerDomain: "~iac:tf-outputs-cloudcli//cloudcli_server_domain~"
