apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argocd-iac-plugin-helm-with-args
spec:
  init:
    command: ["argocd_iac_plugin.py", "init", "."]
  generate:
    command: ["sh", "-c"]
    args: ['argocd_iac_plugin.py generate . "$ARGOCD_APP_NAME" "$ARGOCD_APP_NAMESPACE" ${ARGOCD_ENV_helm_args}']
