apiVersion: batch/v1
kind: CronJob
metadata:
  name: certbot
spec:
  schedule: "0 0,12 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      completions: 1
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: certbot
          containers:
            - name: certbot
              image: {{ .Values.certbot_image }}
              command:
                - bash
                - -c
                - |
                  certbot_.py "{{ .Values.root_domain }}" "{{ .Values.letsencrypt_email }}" --renew --ssl-secret-name=default-ssl-certificate "--rancher-private-ip={{ .Values.rancher_private_ip }}"
              env:
                - name: CLOUDFLARE_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare
                      key: api_token
              volumeMounts:
                - name: certbot
                  mountPath: /etc/letsencrypt
                  subPath: etc_letsencrypt
                - name: certbot
                  mountPath: /var/lib/letsencrypt
                  subPath: var_lib_letsencrypt
                - name: ssh-access-point
                  mountPath: /ssh-access-point
                  readOnly: true
          volumes:
            - name: certbot
              nfs:
                path: /storage/certbot-{{ .Values.root_domain }}
                server: {{ .Values.nfs_private_ip }}
            - name: ssh-access-point
              secret:
                secretName: ssh-access-point
