{{/*apiVersion: crd.projectcalico.org/v1*/}}
{{/*kind: KubeControllersConfiguration*/}}
{{/*metadata:*/}}
{{/*  name: default*/}}
{{/*spec:*/}}
{{/*  controllers:*/}}
{{/*    namespace:*/}}
{{/*      reconcilerPeriod: 5m0s*/}}
{{/*    node:*/}}
{{/*      leakGracePeriod: 15m0s*/}}
{{/*      reconcilerPeriod: 5m0s*/}}
{{/*      syncLabels: Enabled*/}}
{{/*      hostEndpoint:*/}}
{{/*        autoCreate: Enabled*/}}
{{/*    policy:*/}}
{{/*      reconcilerPeriod: 5m0s*/}}
{{/*    serviceAccount:*/}}
{{/*      reconcilerPeriod: 5m0s*/}}
{{/*    workloadEndpoint:*/}}
{{/*      reconcilerPeriod: 5m0s*/}}
{{/*  etcdV3CompactionPeriod: 10m0s*/}}
{{/*  healthChecks: Enabled*/}}
{{/*  logSeverityScreen: Info*/}}
{{/*  prometheusMetricsPort: 9094*/}}
