apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cluster-admin
spec:
  selector:
    matchLabels:
      name: cluster-admin
  template:
    metadata:
      labels:
        name: cluster-admin
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
        - operator: Exists
          effect: NoExecute
      initContainers:
        - name: ssh-authorized-keys
          # Pulled Dec 12, 2022
          image: python:3.8@sha256:7c5b3ec91b7e4131dead176d824ddf317e6c19fe1ae38c54ec0ae6038908dd18
          command:
            - python3
            - -c
            - |
              import os
              with open('/hostssh/authorized_keys', 'r') as f:
                authorized_keys = f.read()
              for k, v in os.environ.items():
                if k.startswith('SSHKEY_'):
                  k = k.replace('SSHKEY_', '')
                  if v not in authorized_keys:
                    with open('/hostssh/authorized_keys', 'a') as f:
                      f.write(f"\n\n# {k}\n{v}\n")
                    print(f'Added {k} to authorized_keys')
          envFrom:
            - configMapRef:
                name: ssh-authorized-keys
          volumeMounts:
            - name: hostssh
              mountPath: /hostssh
        - name: sshd
          # Built from docker/certbot on Dec 11, 2022
          # We use this image because it contains the dependencies we need
          image: ghcr.io/kamatera/kamateratoolbox-iac-certbot:8433ac3d1ec7ee901afb3a8894d8a251d5a409dc
          command:
            - bash
            - -c
            - |
              if ! [ -f /mnt/host/etc/systemd/system/ssh.socket.d/addresses.conf ]; then
                INTERNAL_IP=$(echo $(ip -4 addr show dev eth0 | grep inet) | cut -d' ' -f2 | cut -d'/' -f1)
                if [ -z "$INTERNAL_IP" ]; then
                  echo failed to get internal ip && exit 1
                fi &&\
                TEMPFILE="$(mktemp)" &&\
                cp /mnt/ssh-access-point/privatekey $TEMPFILE &&\
                chmod 400 $TEMPFILE &&\
                ssh -i $TEMPFILE -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$INTERNAL_IP "
                  mkdir -p /etc/systemd/system/ssh.socket.d &&\
                  echo ListenAddress $INTERNAL_IP > /etc/systemd/system/ssh.socket.d/addresses.conf &&\
                  systemctl daemon-reload
                "
              fi
          volumeMounts:
            - name: host
              mountPath: /mnt/host
            - name: ssh-access-point
              mountPath: /mnt/ssh-access-point
      containers:
        - name: pause
          image: k8s.gcr.io/pause:3.2
      volumes:
        - name: hostssh
          hostPath:
            path: /root/.ssh
        - name: host
          hostPath:
            path: /
        - name: ssh-access-point
          secret:
            secretName: ssh-access-point
