apiVersion: batch/v1
kind: CronJob
metadata:
  name: ssh-authorized-keys
spec:
  schedule: "33 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      completions: 1
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: ssh-authorized-keys
              # Pulled Dec 12, 2022
              image: python:3.8@sha256:7c5b3ec91b7e4131dead176d824ddf317e6c19fe1ae38c54ec0ae6038908dd18
              command:
                - python3
                - -c
                - |
                  import time
                  time.sleep(86400)
              envFrom:
                - configMapRef:
                    name: ssh-authorized-keys
              volumeMounts:
                - name: hostssh
                  mountPath: /hostssh
          volumes:
            - name: hostssh
              hostPath:
                path: /root/.ssh
