apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.yaml
- argocd-apps.yaml

patchesStrategicMerge:
- patch-argocd-server-deployment.yaml
- patch-argocd-cm.yaml
- patch-argocd-repo-server-deploy.yaml
