apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        # built from docker/argocd_plugin on Dec 13, 2022
        image: ghcr.io/kamatera/kamateratoolbox-iac-argocd-plugin:e7ed7065326a1cdac1aa9961e237cfaf0c7bbc6a
        securityContext:
          readOnlyRootFilesystem: false
        env:
        - name: AVP_DEBUG
          value: "yes"
        - name: AVP_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: argocd-vault-plugin-credentials
              key: AVP_ROLE_ID
        - name: AVP_SECRET_ID
          valueFrom:
            secretKeyRef:
              name: argocd-vault-plugin-credentials
              key: AVP_SECRET_ID
        - name: VAULT_ADDR
          valueFrom:
            secretKeyRef:
              name: argocd-vault-plugin-credentials
              key: VAULT_ADDR
      automountServiceAccountToken: true
      serviceAccountName: argocd-server
