apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        # built from docker/argocd_plugin on Dec 8, 2022
        image: ghcr.io/kamatera/kamateratoolbox-iac-argocd-plugin:60388d70326528e2f4360ee4b38bfeab3659ac4f
        securityContext:
          readOnlyRootFilesystem: false
        env:
        - name: AVP_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: argocd-vault-plugin-credentials
              key: AVP_ROLE_ID
        - name: AVP_SECRET_ID
          valueFrom:
            secretKeyRef:
              name: argocd-vault-plugin-credentials
              key: AVP_SECRET_ID
        - name: VAULT_ADDR
          valueFrom:
            secretKeyRef:
              name: argocd-vault-plugin-credentials
              key: VAULT_ADDR
      automountServiceAccountToken: true
      serviceAccountName: argocd-server
